# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 952af00ee6a967106e46e6d95ff8556a6b628c6b2a568d5adcd73cc85f7922ede114a436273b84bea1e310a2c1c9d6e59e677448d02610ece0cc4f51af659eb5

test:
  secret_key_base: e8bbb5d0fff773f6a1a08e42fc600503e373c1b07d465d7f3f19fa117d38bec323a18063f6dab054644b60e17f00e5fd704349da5f5d6b99cac4d8d18537aec5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
